"""esquema inicial SGO v3 - ontologia por objetos

Revision ID: 4a19d47fd005
Revises: 
Create Date: 2026-09-08 20:00:55.165288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a19d47fd005'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenios_colectivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('tiene_fondo_cese_laboral', sa.Integer(), server_default='0', nullable=True),
    sa.Column('regimen_indemnizatorio', sa.Text(), nullable=True),
    sa.Column('sindicato', sa.Text(), nullable=True),
    sa.Column('obra_social', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('funciones_organizacionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tabla', sa.Text(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('accion', sa.Text(), nullable=False),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.Column('usuario', sa.Text(), server_default='sistema', nullable=True),
    sa.Column('timestamp', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mecanismos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('grupo', sa.Text(), nullable=False),
    sa.Column('frecuencia', sa.Text(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('documento', sa.Text(), nullable=True),
    sa.Column('emite', sa.Text(), nullable=True),
    sa.Column('recibe', sa.Text(), nullable=True),
    sa.Column('estado_relevado', sa.Text(), nullable=True),
    sa.Column('vigente', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('perfiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), server_default='borrador', nullable=True),
    sa.Column('origen', sa.Text(), server_default='armado', nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_por', sa.Text(), server_default='sistema', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), server_default='pendiente', nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('procedimientos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('area', sa.Text(), nullable=False),
    sa.Column('nivel_riesgo', sa.Text(), server_default='medio', nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tiene_nivel_urgente', sa.Integer(), server_default='1', nullable=True),
    sa.Column('tiene_nivel_emergencia', sa.Integer(), server_default='1', nullable=True),
    sa.Column('formularios_asociados', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipos_de_capacitacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=True),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('organismo_emisor', sa.Text(), nullable=True),
    sa.Column('vigencia_meses', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Text(), server_default='documento', nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('url_o_referencia', sa.Text(), nullable=True),
    sa.Column('duracion_estimada', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('apellido', sa.Text(), nullable=False),
    sa.Column('legajo', sa.Text(), nullable=True),
    sa.Column('cuit', sa.Text(), nullable=True),
    sa.Column('convenio_id', sa.Integer(), nullable=True),
    sa.Column('antiguedad_anos', sa.Float(), nullable=True),
    sa.Column('estado_legajo', sa.Text(), server_default='completo', nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenios_colectivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('puestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('area', sa.Text(), nullable=False),
    sa.Column('nivel', sa.Text(), nullable=False),
    sa.Column('cardinalidad_esperada', sa.Text(), server_default='unica_en_la_empresa', nullable=False),
    sa.Column('proposito', sa.Text(), nullable=True),
    sa.Column('limites_autoridad', sa.Text(), nullable=True),
    sa.Column('convenio_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=True),
    sa.Column('vigente', sa.Integer(), server_default='1', nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenios_colectivos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('registro_cumplimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mecanismo_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Text(), nullable=False),
    sa.Column('causa', sa.Text(), nullable=True),
    sa.Column('accion_correctiva', sa.Text(), nullable=True),
    sa.Column('registrado_por', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['mecanismo_id'], ['mecanismos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mecanismo_id', 'periodo')
    )
    op.create_table('actividades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('area', sa.Text(), nullable=False),
    sa.Column('nivel', sa.Text(), nullable=False),
    sa.Column('competencia', sa.Text(), nullable=True),
    sa.Column('es_critica', sa.Integer(), server_default='0', nullable=True),
    sa.Column('frecuencia', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Integer(), server_default='1', nullable=True),
    sa.Column('puesto_codigo', sa.Text(), nullable=True),
    sa.Column('funcion_organizacional_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['funcion_organizacional_id'], ['funciones_organizacionales.id'], ),
    sa.ForeignKeyConstraint(['puesto_codigo'], ['puestos.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.create_index('idx_actividades_area', ['area'], unique=False)
        batch_op.create_index('idx_actividades_puesto', ['puesto_codigo'], unique=False)

    op.create_table('asignaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('puesto_codigo', sa.Text(), nullable=True),
    sa.Column('perfil_id', sa.Integer(), nullable=True),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.Column('etapa', sa.Text(), nullable=True),
    sa.Column('estado', sa.Text(), server_default='activa', nullable=True),
    sa.Column('fecha_inicio', sa.Text(), nullable=True),
    sa.Column('fecha_fin_estimada', sa.Text(), nullable=True),
    sa.Column('fecha_fin_real', sa.Text(), nullable=True),
    sa.Column('condicion_salida', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles.id'], ),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], ),
    sa.ForeignKeyConstraint(['puesto_codigo'], ['puestos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asignaciones', schema=None) as batch_op:
        batch_op.create_index('idx_asignaciones_persona', ['persona_id'], unique=False)
        batch_op.create_index('idx_asignaciones_planta', ['planta_id'], unique=False)
        batch_op.create_index('idx_asignaciones_puesto', ['puesto_codigo'], unique=False)

    op.create_table('habilitaciones_persona',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('tipo_capacitacion_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.Column('fecha_obtencion', sa.Text(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Text(), nullable=True),
    sa.Column('estado', sa.Text(), server_default='vigente', nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ),
    sa.ForeignKeyConstraint(['tipo_capacitacion_id'], ['tipos_de_capacitacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('habilitaciones_persona', schema=None) as batch_op:
        batch_op.create_index('idx_habilitaciones_vencimiento', ['fecha_vencimiento'], unique=False)

    op.create_table('indicadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('area', sa.Text(), nullable=False),
    sa.Column('formula', sa.Text(), nullable=True),
    sa.Column('frecuencia', sa.Text(), nullable=True),
    sa.Column('fuente_dato', sa.Text(), nullable=True),
    sa.Column('responsable_carga_puesto_codigo', sa.Text(), nullable=True),
    sa.Column('responsable_uso_puesto_codigo', sa.Text(), nullable=True),
    sa.Column('umbral_verde', sa.Text(), nullable=True),
    sa.Column('umbral_amarillo', sa.Text(), nullable=True),
    sa.Column('umbral_rojo', sa.Text(), nullable=True),
    sa.Column('activo', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['responsable_carga_puesto_codigo'], ['puestos.codigo'], ),
    sa.ForeignKeyConstraint(['responsable_uso_puesto_codigo'], ['puestos.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('mecanismo_puestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mecanismo_id', sa.Integer(), nullable=False),
    sa.Column('puesto_codigo', sa.Text(), nullable=False),
    sa.Column('rol', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['mecanismo_id'], ['mecanismos.id'], ),
    sa.ForeignKeyConstraint(['puesto_codigo'], ['puestos.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mecanismo_id', 'puesto_codigo', 'rol')
    )
    op.create_table('pasos_procedimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procedimiento_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('responsable_puesto_codigo', sa.Text(), nullable=True),
    sa.Column('documento', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['procedimiento_id'], ['procedimientos.id'], ),
    sa.ForeignKeyConstraint(['responsable_puesto_codigo'], ['puestos.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedimiento_puestos',
    sa.Column('procedimiento_id', sa.Integer(), nullable=False),
    sa.Column('puesto_codigo', sa.Text(), nullable=False),
    sa.Column('rol', sa.Text(), server_default='ejecuta', nullable=True),
    sa.ForeignKeyConstraint(['procedimiento_id'], ['procedimientos.id'], ),
    sa.ForeignKeyConstraint(['puesto_codigo'], ['puestos.codigo'], ),
    sa.PrimaryKeyConstraint('procedimiento_id', 'puesto_codigo')
    )
    op.create_table('puesto_funciones',
    sa.Column('puesto_codigo', sa.Text(), nullable=False),
    sa.Column('funcion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcion_id'], ['funciones_organizacionales.id'], ),
    sa.ForeignKeyConstraint(['puesto_codigo'], ['puestos.codigo'], ),
    sa.PrimaryKeyConstraint('puesto_codigo', 'funcion_id')
    )
    op.create_table('relaciones_reporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puesto_codigo', sa.Text(), nullable=False),
    sa.Column('relacionado_codigo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['puesto_codigo'], ['puestos.codigo'], ),
    sa.ForeignKeyConstraint(['relacionado_codigo'], ['puestos.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puesto_codigo', 'relacionado_codigo', 'tipo')
    )
    with op.batch_alter_table('relaciones_reporte', schema=None) as batch_op:
        batch_op.create_index('idx_relaciones_reporte_puesto', ['puesto_codigo'], unique=False)

    op.create_table('roles_transicion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puesto_id', sa.Integer(), nullable=False),
    sa.Column('fecha_estimada_extincion', sa.Text(), nullable=True),
    sa.Column('condicion_extincion', sa.Text(), nullable=True),
    sa.Column('puesto_absorbente_codigo', sa.Text(), nullable=True),
    sa.Column('puesto_monitor_codigo', sa.Text(), nullable=True),
    sa.Column('estado', sa.Text(), server_default='vigente', nullable=True),
    sa.ForeignKeyConstraint(['puesto_absorbente_codigo'], ['puestos.codigo'], ),
    sa.ForeignKeyConstraint(['puesto_id'], ['puestos.id'], ),
    sa.ForeignKeyConstraint(['puesto_monitor_codigo'], ['puestos.codigo'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('puesto_id')
    )
    op.create_table('actividad_capacitaciones',
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('tipo_capacitacion_id', sa.Integer(), nullable=False),
    sa.Column('obligatoria', sa.Integer(), server_default='1', nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['tipo_capacitacion_id'], ['tipos_de_capacitacion.id'], ),
    sa.PrimaryKeyConstraint('actividad_id', 'tipo_capacitacion_id')
    )
    op.create_table('mediciones_indicador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicador_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.Text(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['indicador_id'], ['indicadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicador_id', 'periodo')
    )
    op.create_table('perfil_actividades',
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), server_default='0', nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles.id'], ),
    sa.PrimaryKeyConstraint('perfil_id', 'actividad_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfil_actividades')
    op.drop_table('mediciones_indicador')
    op.drop_table('actividad_capacitaciones')
    op.drop_table('roles_transicion')
    with op.batch_alter_table('relaciones_reporte', schema=None) as batch_op:
        batch_op.drop_index('idx_relaciones_reporte_puesto')

    op.drop_table('relaciones_reporte')
    op.drop_table('puesto_funciones')
    op.drop_table('procedimiento_puestos')
    op.drop_table('pasos_procedimiento')
    op.drop_table('mecanismo_puestos')
    op.drop_table('indicadores')
    with op.batch_alter_table('habilitaciones_persona', schema=None) as batch_op:
        batch_op.drop_index('idx_habilitaciones_vencimiento')

    op.drop_table('habilitaciones_persona')
    with op.batch_alter_table('asignaciones', schema=None) as batch_op:
        batch_op.drop_index('idx_asignaciones_puesto')
        batch_op.drop_index('idx_asignaciones_planta')
        batch_op.drop_index('idx_asignaciones_persona')

    op.drop_table('asignaciones')
    with op.batch_alter_table('actividades', schema=None) as batch_op:
        batch_op.drop_index('idx_actividades_puesto')
        batch_op.drop_index('idx_actividades_area')

    op.drop_table('actividades')
    op.drop_table('registro_cumplimiento')
    op.drop_table('puestos')
    op.drop_table('personas')
    op.drop_table('tipos_de_capacitacion')
    op.drop_table('procedimientos')
    op.drop_table('plantas')
    op.drop_table('perfiles')
    op.drop_table('mecanismos')
    op.drop_table('historial')
    op.drop_table('funciones_organizacionales')
    op.drop_table('convenios_colectivos')
    # ### end Alembic commands ###
