"""agrega actividades cedidas

Revision ID: 4afec79fdaed
Revises: 3a48628df9cf
Create Date: 2026-10-05 23:20:14.962628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4afec79fdaed'
down_revision: Union[str, Sequence[str], None] = '3a48628df9cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actividades_cedidas',
    sa.Column('asignacion_id', sa.Integer(), nullable=False),
    sa.Column('actividad_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades.id'], ),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignaciones.id'], ),
    sa.PrimaryKeyConstraint('asignacion_id', 'actividad_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actividades_cedidas')
    # ### end Alembic commands ###
