"""agrega formulario como objeto propio

Revision ID: 4d7460dde13c
Revises: f23be8a43891
Create Date: 2026-10-02 22:47:54.233561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7460dde13c'
down_revision: Union[str, Sequence[str], None] = 'f23be8a43891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formularios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Text(), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('origen', sa.Text(), nullable=True),
    sa.Column('emisor', sa.Text(), nullable=True),
    sa.Column('receptor', sa.Text(), nullable=True),
    sa.Column('frecuencia', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.Column('updated_at', sa.Text(), server_default=sa.text("(datetime('now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('mecanismo_formularios',
    sa.Column('mecanismo_id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ),
    sa.ForeignKeyConstraint(['mecanismo_id'], ['mecanismos.id'], ),
    sa.PrimaryKeyConstraint('mecanismo_id', 'formulario_id')
    )
    op.create_table('procedimiento_formularios',
    sa.Column('procedimiento_id', sa.Integer(), nullable=False),
    sa.Column('formulario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['formulario_id'], ['formularios.id'], ),
    sa.ForeignKeyConstraint(['procedimiento_id'], ['procedimientos.id'], ),
    sa.PrimaryKeyConstraint('procedimiento_id', 'formulario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedimiento_formularios')
    op.drop_table('mecanismo_formularios')
    op.drop_table('formularios')
    # ### end Alembic commands ###
