"""agrega responsable_texto_original a pasos_procedimiento

Revision ID: f23be8a43891
Revises: 4a19d47fd005
Create Date: 2026-09-09 02:14:31.198177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23be8a43891'
down_revision: Union[str, Sequence[str], None] = '4a19d47fd005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasos_procedimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable_texto_original', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasos_procedimiento', schema=None) as batch_op:
        batch_op.drop_column('responsable_texto_original')

    # ### end Alembic commands ###
